* Небольшая напоминалка при разработке интерфейса
Итак, все страницы (ну почти все) можно условно разделить на две
группы:

1. Добавление/редактирование
2. Список
3. Описание

Страничек в приложении получается достаточно много, но все они
примерно такие. Страница описания в каждом "разделе" только одна, а
именно "Сделка", "Клиент", "Дело". Но в случае списка, добавления и
редактирования компоненты можно использовать несколько раз. Тоесть,
 редактирование и добавление -- это одна и та же страница, только в
случае редактирования поля уже заполнены заранее. Списко клиентов,
список клиентов в сделке, список дел и пр. -- все это списки, иначе
говоря, нужно стараться использовать один ```.qml``` файл в нужных
местах по максимуму.

Далее, тулбар. Тулбар на каждой странице разное, но также следует
одинаковым шаблонам. Нужно, чтобы странца могла контролировать кнопки
в тулбаре. Например, кнопка вызова меню навигации есть всегда и
везде. Кнопка "назад" появляется на таких страницах как
"добавление/редакитрование" и "просомтр клиента", например. В списках
в нем есть кнопка "+", сортировка (еще не понятно как), фильтр
наверное; в "просмотре" -- карандашик, тоесть, "редактрировать".

вот пока как-то так
