*** Требования к ПО

Органайзер риелтора -- удобный помошник в риелторской деятельности.

**** Необходимые функции:

***** Просмотр текущих дел 
   
   * встречи
   * осмотры
   * оформление документов
   * ...
   
   Каждое событие привязано к конкретной сделке. По сути, сделка
   состоит из набора событий в определенном порядке. Это может быть аренда
   или продажа квартиры. У каждой сделки также есть стоимость и процент,
   который получит владелец. Сделка может быть помечена как успешная
   / неудачная. 
   
*****  Управление базой клиентов
   
   Приложение содержит список контаков клиентов. Для удобства навигации,
   каждый контакт может быть ассоциирован со сделкой. 

*****  Тайм-менеджмент
   
   Каждое событие имеет запланированный срок выполнения. Для удобства,
   должна быть возможность просмотра списка ближайших дел по текущим сделкам.

*****  Итоги и отчетность

   Должна быть возможнсть просмотра финансовой и временной статистики,
   а именно: 
   
   * количество проведенных сделок, процент неудач
   * доход
   * затраченное время, в среднем
     
   Вся статистика должна расчитываться в определенный период, динамику
   изменения каждого значения можно проследить на графике.
